name: Update GitHub Stats

on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate GitHub Stats
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=dhDSouza&show_icons=true&include_all_commits=true&count_private=true&theme=react
          path: profile/stats.svg
          token: ${{ secrets.GH_STATS_TOKEN  }}

      - name: Generate Top Languages
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=dhDSouza&layout=compact&langs_count=10&theme=react&hide=css
          path: profile/top-langs.svg
          token: ${{ secrets.GH_STATS_TOKEN  }}

      - name: Commit updated cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/*.svg

          git diff --cached --quiet || git commit -m "chore: update GitHub stats"

          git push
